#development:
  #FACEBOOK_KEY: ''
  #FACEBOOK_SECRET: ''
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
#staging:
  #FACEBOOK_KEY: ''
  #FACEBOOK_SECRET: ''
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
#production:
  #FACEBOOK_KEY: ''
  #FACEBOOK_SECRET: ''
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
